name: Prueba concepto 
on:
  push:
    branches: [ trunk, 'feature/**' ]
  pull_request:
    branches: [ trunk, 'feature/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: echo "Checking out code..."