trigger:
- trunk

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: '1. Instalar Node.js'

- script: npm ci
  displayName: '2. Instalar librerías del proyecto'


- script: |
    npx cypress run --browser chrome --headless
  displayName: '3. Ejecutar Cypress E2E'
  continueOnError: true


- task: PublishHtmlReport@1
  condition: always()
  inputs:
    reportDir: '$(System.DefaultWorkingDirectory)/evidencia/reporte/index.html'
    tabName: 'Reporte Cypress'
  displayName: '4. Publicar Pestaña HTML'