name: Prueba concepto 
on:
  push:
    branches: [ trunk, 'feature/**' ]
  pull_request:
    branches: [ trunk, 'feature/**' ]
permissions:
  contents: write

jobs:
  # Job 2: Ejecución de pruebas
  automation-workflow:
    runs-on: ubuntu-latest
    environment: Transversal
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Reinstalar rápido desde cache (Cypress necesita esto)
        run: npm ci 

      - name: Ejecutar Cypress E2E
        run: npx cypress run --browser chrome --headless
        env:
          CYPRESS_SECRET_VALUE: ${{ secrets.SECRET_VALUE }}
        continue-on-error: true

      - name: Deploy Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./evidencia/reporte     
